### PR TITLE
#28 - correctly adds serverless env file

### PR DESCRIPTION
**Pull request by gurungrahul2**

### CODE REVIEW

**Comment by gurungrahul2** [comment]
@aashutoshrathi it works fine on my local machine :smile:

**Comment by aashutoshrathi** [comment]
Why Travis wasn't triggered?

**Comment by aashutoshrathi** [comment]
Let's check by merging

**Comment by gurungrahul2** [comment]
Maybe because of that old cat command.

**Comment by gurungrahul2** [comment]
@aashutoshrathi  I got it, we can't proceed until pull #26   runs, because it is in master, but it is failing thus new PR are not getting triggered, we have to remove that file, especially from Travis.

**Pull request merged**
